/* Pair data: romantic compatibility (45 pairs) and trait similarity (36 pairs).
 * Scores are heuristics about default friction/complement patterns between
 * average-health examples of each type — NOT predictions. Health level,
 * instincts, and plain effort matter far more than type math.
 *
 * Key format: "a-b" with a <= b.
 */

function pairKey(a, b) {
  return a <= b ? a + "-" + b : b + "-" + a;
}

const PAIRS = {
  "1-1": { s: 70, t: "Two Reformers",
    blurb: "Two reformers build an orderly, principled life and genuinely admire each other's integrity.",
    spark: "Shared standards — finally, someone who also cares about doing things right.",
    friction: "Two inner critics with different rulebooks can turn the kitchen into a courtroom.",
    growth: "Agree whose standard governs which domain, and schedule deliberate imperfection together." },
  "1-2": { s: 82, t: "The Improver & The Helper",
    blurb: "Complementary duty: one perfects the world while the other tends its people.",
    spark: "One relaxes in Two's warmth; Two feels safe in One's reliability.",
    friction: "One's critique lands on Two as personal rejection; Two's emotional appeals read to One as manipulation.",
    growth: "One says appreciation out loud; Two states needs directly instead of earning them." },
  "1-3": { s: 72, t: "The Idealist & The Achiever",
    blurb: "Two driven self-improvers who respect each other's competence and get a great deal done.",
    spark: "Mutual admiration for capability, and a household that runs like a well-managed project.",
    friction: "Three cuts corners for the win; One would rather lose correctly.",
    growth: "Let Three teach flexibility and One teach integrity — without keeping score." },
  "1-4": { s: 74, t: "The Rule-Keeper & The Romantic",
    blurb: "These two sit on each other's connecting line, so the bond runs surprisingly deep when it's healthy.",
    spark: "Four thaws One's restraint; One steadies Four's storms.",
    friction: "One finds Four undisciplined; Four finds One emotionally beige.",
    growth: "One learns feelings aren't errors; Four learns structure isn't a cage." },
  "1-5": { s: 76, t: "The Principled & The Private",
    blurb: "Reserved, cerebral, and self-contained — a quiet partnership of deep mutual respect.",
    spark: "Low drama, high standards, and plenty of contented parallel solitude.",
    friction: "Both withhold: One withholds approval, Five withholds presence.",
    growth: "Schedule real engagement — warmth won't generate itself from principle or analysis." },
  "1-6": { s: 74, t: "Duty & Loyalty",
    blurb: "Two responsibility-first types who build a dependable, committed home.",
    spark: "Shared vigilance: bills paid, promises kept, contingencies covered.",
    friction: "Six's doubt reads as disloyalty to One; One's certainty reads as rigidity to Six.",
    growth: "Name anxieties as anxieties — not as moral failures or emergencies." },
  "1-7": { s: 84, t: "Discipline & Delight",
    blurb: "Growth-line opposites: the disciplined idealist and the joyful escape artist complete each other.",
    spark: "Seven is the vacation One never takes; One is the ground Seven never finds.",
    friction: "Seven's reframing feels evasive to One; One's rules feel like prison to Seven.",
    growth: "Trade gifts on purpose: One books the spontaneity, Seven keeps one promise at a time." },
  "1-8": { s: 68, t: "The Judge & The Outlaw",
    blurb: "Two strong-willed gut types with very different relationships to the rules.",
    spark: "Mutual respect for backbone — neither wants a pushover.",
    friction: "Eight breaks rules One lives by; both dig in, and neither apologizes first.",
    growth: "Pick shared causes and aim the combined force outward, not at each other." },
  "1-9": { s: 83, t: "The Engine & The Calm",
    blurb: "A classic pairing: the reformer's drive wrapped in the peacemaker's acceptance.",
    spark: "Nine's acceptance is medicine for One's critic; One's direction is medicine for Nine's drift.",
    friction: "One pushes, Nine stalls — and the harder the push, the deeper the stall.",
    growth: "One softens the 'shoulds'; Nine gives real yeses and real nos." },
  "2-2": { s: 72, t: "Two Helpers",
    blurb: "Two givers out-give each other in a warm, quietly competitive dance.",
    spark: "Endless attunement — both speak fluent care.",
    friction: "Nobody admits needs, so both keep score of unappreciated giving.",
    growth: "Practice receiving on schedule; let the other person give first." },
  "2-3": { s: 78, t: "The Charmer & The Star",
    blurb: "A socially gifted, high-functioning duo that everyone loves to invite.",
    spark: "Two makes Three feel loved beyond the résumé; Three gives Two a star worth supporting.",
    friction: "Both perform: feelings get staged, postponed, and eventually misplaced.",
    growth: "Trade image for honesty a little at a time — start with tired, scared, and ordinary." },
  "2-4": { s: 80, t: "The Giver & The Dreamer",
    blurb: "A heart-center pair: one reaches outward for connection, one reaches inward for meaning.",
    spark: "Four's depth fascinates Two; Two's devotion steadies Four.",
    friction: "Four withdraws to feel real; Two pursues to feel needed — a perfect chase loop.",
    growth: "Two gives space as a gift; Four says 'stay' out loud when they mean it." },
  "2-5": { s: 70, t: "The Pursuer & The Hermit",
    blurb: "Maximum contrast in the need for contact — and real tenderness when the treaty holds.",
    spark: "Five's self-sufficiency intrigues Two; Two's warmth slips past Five's defenses.",
    friction: "Two reads privacy as rejection; Five reads care as invasion.",
    growth: "Negotiate contact like diplomats: guaranteed together-time, guaranteed alone-time." },
  "2-6": { s: 77, t: "Warmth & Loyalty",
    blurb: "A devoted, watchful couple — affection on one side, allegiance on the other, and plenty of both.",
    spark: "Two's steadiness slowly earns Six's trust; Six's loyalty answers Two's fear of being unwanted.",
    friction: "Six's suspicion questions Two's motives; Two's flattery feeds Six's doubt.",
    growth: "Replace tests and hints with plain asks and plain answers." },
  "2-7": { s: 75, t: "The Host & The Party",
    blurb: "Sunny, social, and generous — the couple whose table everyone wants a seat at.",
    spark: "Generosity meets fun; the calendar fills itself.",
    friction: "Both dodge the dark stuff — pain gets catered to, not addressed.",
    growth: "Sit with one hard feeling together before planning the next celebration." },
  "2-8": { s: 85, t: "The Nurturer & The Protector",
    blurb: "A legendary enneagram match: strength that shelters, warmth that disarms.",
    spark: "Eight's strength makes Two feel safe; Two's warmth reaches the tenderness Eight hides.",
    friction: "Eight's bluntness bruises; Two's indirect influence feels like manipulation to Eight.",
    growth: "Two practices directness; Eight practices gentleness — each already has it in reserve." },
  "2-9": { s: 79, t: "Two Accommodators",
    blurb: "A genuinely kind, low-conflict home with warm and mild emotional weather.",
    spark: "Both attune instinctively; caring for each other comes easily.",
    friction: "Nobody claims the steering wheel — decisions and resentments both drift.",
    growth: "Take turns choosing; say preferences before merging them." },
  "3-3": { s: 68, t: "The Power Couple",
    blurb: "Two achievers sprinting side by side, trading wins and mutual admiration.",
    spark: "A shared allergy to mediocrity — this pair gets places.",
    friction: "The relationship becomes another project, and intimacy loses to the calendar.",
    growth: "Win at rest: schedule unproductive time where nothing gets performed." },
  "3-4": { s: 73, t: "Polish & Depth",
    blurb: "Neighboring heart types with opposite strategies for mattering.",
    spark: "Four gives Three permission to feel; Three gives Four traction in the world.",
    friction: "Three's polish looks fake to Four; Four's intensity looks inefficient to Three.",
    growth: "Three shares one unpolished truth; Four celebrates one ordinary win." },
  "3-5": { s: 69, t: "The Doer & The Thinker",
    blurb: "Competence admired across a comfortable distance.",
    spark: "No clinginess — two capable adults with genuinely interesting lives.",
    friction: "Feelings go unprocessed by mutual agreement until the distance is the relationship.",
    growth: "Put connection on the roadmap — deliberately, like the projects it competes with." },
  "3-6": { s: 74, t: "Ambition & Allegiance",
    blurb: "Confidence and caution on the same team — each supplies what the other skips.",
    spark: "Six covers the risks Three ignores; Three supplies the confidence Six borrows.",
    friction: "Six's doubts puncture Three's optimism; Three's image management feeds Six's suspicion.",
    growth: "Three tells the whole truth including setbacks; Six voices trust as often as doubt." },
  "3-7": { s: 79, t: "The Highlight Reel",
    blurb: "Fast, bright, and busy — the enneagram's highest-RPM couple.",
    spark: "Endless plans, quick minds, shared momentum.",
    friction: "Nobody slows down, so failure and sadness have nowhere to land.",
    growth: "Make it safe to be unimpressive with each other." },
  "3-8": { s: 77, t: "The Empire Builders",
    blurb: "Two forces of will who could run a company — or a small country — together.",
    spark: "Shared drive and zero tolerance for excuses.",
    friction: "Competition creeps in; Eight demands realness while Three manages image.",
    growth: "Say 'same team' explicitly — Eight leads with respect, Three with honesty." },
  "3-9": { s: 81, t: "The Engine & The Harbor",
    blurb: "Motion and stillness in a naturally complementary orbit.",
    spark: "Nine grounds Three's racing; Three animates Nine's easy pace.",
    friction: "Three's agenda quietly swallows Nine's; Nine's slowness frustrates Three.",
    growth: "Three asks 'what do you want?' and actually waits; Nine answers before merging." },
  "4-4": { s: 66, t: "Two Romantics",
    blurb: "A beautiful, stormy sea — profound understanding, shared turbulence.",
    spark: "Finally, someone who doesn't flinch at depth.",
    friction: "Both amplify feelings and both withdraw dramatically; nobody plays ballast.",
    growth: "Assign lighthouse duty: when one dives, the other stays on shore." },
  "4-5": { s: 82, t: "The Romantic & The Observer",
    blurb: "A private world of depth and ideas that outsiders never quite decode.",
    spark: "Both prize authenticity and inner life; the connection feels rare because it is.",
    friction: "Four needs emotional response that Five rations; both withdraw and call it being understood.",
    growth: "Five shows feeling in real time; Four lets thinking cool the flood." },
  "4-6": { s: 72, t: "Two Doubters",
    blurb: "One doubts the self, the other doubts the world — both understand uncertainty.",
    spark: "Six's loyalty is the constancy Four craves; Four's depth honors Six's hidden intensity.",
    friction: "Four's dramatics trip Six's alarms; Six's testing feels like distrust of Four's authenticity.",
    growth: "Reassure each other on purpose, in words, before the spiral starts." },
  "4-7": { s: 76, t: "Depth & Flight",
    blurb: "Opposite strategies for pain make each the other's missing hemisphere.",
    spark: "Seven lightens Four; Four deepens Seven.",
    friction: "Seven reframes exactly what Four needs to feel; Four insists on sadness Seven can't sit in.",
    growth: "Seven stays five more minutes in the hard talk; Four comes along on the adventure." },
  "4-8": { s: 78, t: "Intensity Meets Intensity",
    blurb: "Two all-in temperaments who despise pretense and can handle each other at full volume.",
    spark: "Nothing is lukewarm; both feel truly met for the first time.",
    friction: "Eight's bluntness gashes Four's sensitivities; Four's moods read as chaos to Eight.",
    growth: "Eight guards the tone; Four states the need underneath the mood." },
  "4-9": { s: 75, t: "The Storm & The Still Water",
    blurb: "Acceptance meets intensity — soothing for both, until their core wounds collide.",
    spark: "Nine receives Four without judgment; Four wakes Nine's buried inner life.",
    friction: "Four escalates to feel met; Nine numbs to stay safe — each triggers the other's deepest fear.",
    growth: "Nine engages before the escalation; Four turns the volume down one notch, voluntarily." },
  "5-5": { s: 71, t: "Two Observers",
    blurb: "Adjoining libraries, mutual respect, and conversation that's ideas all the way down.",
    spark: "Perfect mutual respect for space — no one is ever crowded.",
    friction: "Two hoarders of self can share a home and never quite meet.",
    growth: "Ritualize contact: standing dinners, walks, one feeling disclosed per week." },
  "5-6": { s: 76, t: "Head-Center Allies",
    blurb: "Analysis and loyalty pooled against an uncertain world.",
    spark: "Five's calm soothes Six; Six's steadfastness warms Five's isolation.",
    friction: "Six needs reassurance Five doesn't emit; Five needs space Six reads as abandonment.",
    growth: "Six asks directly instead of testing; Five volunteers presence before it's requested." },
  "5-7": { s: 78, t: "The Deep Diver & The Wave Hopper",
    blurb: "Connected by an arrow line: breadth meets depth, and both minds light up.",
    spark: "Seven brings Five to life; Five gives Seven's racing mind a place to land.",
    friction: "Seven's pace exhausts Five's battery; Five's retreat bores Seven.",
    growth: "Alternate deliberately: one adventure out, one deep night in — both count as together." },
  "5-8": { s: 80, t: "Quiet Depth & Blunt Force",
    blurb: "An odd-couple chemistry with real staying power — space honored, truth spoken.",
    spark: "Eight protects Five's space and says what it means; Five is unintimidated, which Eight finds rare.",
    friction: "Eight's volume overwhelms; Five's withholding reads to Eight as secrecy — betrayal's cousin.",
    growth: "Eight throttles intensity by choice; Five shares before being asked." },
  "5-9": { s: 74, t: "Two Quiet Worlds",
    blurb: "Gentle orbits, no crowding, deep unspoken comfort.",
    spark: "Effortless peace — neither demands, neither intrudes.",
    friction: "So little friction that nothing moves; withdrawal times inertia equals roommates.",
    growth: "Someone initiates — put wants into words weekly, even small ones." },
  "6-6": { s: 69, t: "Two Guardians",
    blurb: "Deep loyalty on the same watchtower — commitment treated as sacred.",
    spark: "Both take promises seriously; neither will be casually abandoned.",
    friction: "Shared vigilance doubles the alarms — each confirms the other's worst-case scenarios.",
    growth: "Appoint a designated optimist per decision; date the evidence, not the fear." },
  "6-7": { s: 75, t: "The Planner & The Improviser",
    blurb: "Adjacent types with opposite defaults — dread and delight keep each other honest.",
    spark: "Seven melts Six's worry; Six gives Seven's fireworks a launchpad.",
    friction: "Six vetoes what Seven proposes; Seven's escapes look to Six like abandonment.",
    growth: "Six grants two unhedged yeses a month; Seven honors the plan they made." },
  "6-8": { s: 79, t: "The Loyal Skeptic & The Straight Shooter",
    blurb: "Testing meets unwavering — and both finally relax.",
    spark: "Eight never wavers, which answers Six's deepest question; Six's loyalty passes Eight's tests.",
    friction: "Six's testing insults Eight's word; Eight's aggression spikes Six's alarms.",
    growth: "Eight explains instead of commands; Six voices trust in the track record out loud." },
  "6-9": { s: 80, t: "Steadiness Squared",
    blurb: "One of the most comforting pairings: calm that answers vigilance.",
    spark: "Nine's calm is the safety Six scans for; Six's commitment anchors Nine.",
    friction: "Both avoid: Six frets silently, Nine naps through it — issues age in place.",
    growth: "Hold a weekly state-of-us talk with both phones face down." },
  "7-7": { s: 74, t: "Double Fireworks",
    blurb: "The most fun couple at every party, with an infinite shared bucket list.",
    spark: "Yes meets yes; enthusiasm compounds.",
    friction: "Two escape artists — when pain visits, both are already at the airport.",
    growth: "Take turns being the one who stays on the ground." },
  "7-8": { s: 81, t: "Appetite & Power",
    blurb: "A big-living, fast-moving alliance — neither ever dims the other.",
    spark: "Both play offense against life; the energy is enormous.",
    friction: "Eight wants command and Seven wants exit rows — control versus freedom.",
    growth: "Eight offers freedom as a gift; Seven chooses to stay put and says so." },
  "7-9": { s: 78, t: "Sunshine on Still Water",
    blurb: "Optimism and ease — pleasant, low-judgment, and easy to live in.",
    spark: "Seven stirs, Nine steadies, and neither criticizes.",
    friction: "Conflict-avoidance squared: problems get outrun and slept on, never solved.",
    growth: "Practice the two-minute complaint — small, early, survivable." },
  "8-8": { s: 62, t: "Two Storms",
    blurb: "Full-contact honesty and ferocious loyalty — in the same sky as constant thunder.",
    spark: "Nobody else can match this intensity, and both know it.",
    friction: "Neither yields; every disagreement becomes a title fight.",
    growth: "Divide domains of command in peacetime; make yielding a strength ritual, not a defeat." },
  "8-9": { s: 82, t: "The Bulldozer & The Meadow",
    blurb: "A famous complementary match: unstoppable force, immovable peace.",
    spark: "Nine is the one person Eight can't fight with, which melts Eight's armor; Eight moves the world for Nine.",
    friction: "Eight's push meets Nine's stall; Nine goes quiet, and Eight escalates to find them.",
    growth: "Eight invites instead of insists; Nine pushes back early — Eight genuinely loves it." },
  "9-9": { s: 70, t: "Two Peacemakers",
    blurb: "The calmest home in the enneagram — total acceptance, zero pressure.",
    spark: "Complete comfort; neither ever feels judged or rushed.",
    friction: "Merged and mellow — but who are we, and where are we going?",
    growth: "Externalize decisions: lists, coin flips, alternating vetoes — anything but drift." }
};

/* Trait similarity for every distinct pair: what they share, and the tell. */
const SIMILAR = {
  "1-2": { shared: "Both are dutiful, service-minded, and harder on themselves than on anyone else.",
           tell: "One serves the standard; Two serves the person." },
  "1-3": { shared: "Both are disciplined, productive, and quietly competitive about doing well.",
           tell: "One pursues correctness; Three pursues applause." },
  "1-4": { shared: "Both are idealists who measure reality against an inner vision and find it wanting.",
           tell: "One's gap is moral (how things should be); Four's gap is personal (what I'm missing)." },
  "1-5": { shared: "Both are restrained, cerebral, and allergic to sloppiness.",
           tell: "One judges what's right; Five maps what's true." },
  "1-6": { shared: "Both are rule-aware, responsible, and vigilant about what could go wrong.",
           tell: "One obeys the inner critic; Six consults outside authorities — then doubts them." },
  "1-7": { shared: "Both are idealists about how good life could be.",
           tell: "One defers joy for duty; Seven defers duty for joy." },
  "1-8": { shared: "Both are strong-willed gut types who move against what's wrong.",
           tell: "One's anger is moral and metered; Eight's is territorial and free." },
  "1-9": { shared: "Both contain anger and value order and principle — 1w9 and 9w1 blur into each other.",
           tell: "One presses the world to improve; Nine accepts it to stay at peace." },
  "2-3": { shared: "Both are image-aware heart types who read a room instantly — 2w3 and 3w2 blur.",
           tell: "Two earns love by helping; Three earns it by winning." },
  "2-4": { shared: "Both live through relationships and feel things at high resolution.",
           tell: "Two moves toward others' needs; Four dwells in its own longing." },
  "2-5": { shared: "Fewer shared traits than any other pair — yet both secretly fear depending on others.",
           tell: "Two defends against it by being needed; Five by needing nothing." },
  "2-6": { shared: "Both are warm, loyal, and attentive to others' expectations.",
           tell: "Two attaches to be loved; Six attaches to be safe." },
  "2-7": { shared: "Both are upbeat, sociable energizers of other people.",
           tell: "Two orchestrates your enjoyment; Seven chases its own and invites you along." },
  "2-8": { shared: "Both are intense, possessive protectors of their people.",
           tell: "Two protects to stay needed; Eight protects to stay strong." },
  "2-9": { shared: "Both merge with others and forget themselves — the enneagram's great accommodators.",
           tell: "Two merges actively to be appreciated; Nine merges passively to avoid friction." },
  "3-4": { shared: "Both are identity-focused heart types preoccupied with being seen — 3w4 and 4w3 blur.",
           tell: "Three curates the image; Four curates the truth." },
  "3-5": { shared: "Both are competence-first types who sideline feelings to function.",
           tell: "Three performs competence publicly; Five hoards it privately." },
  "3-6": { shared: "Both scan constantly for how they're being evaluated.",
           tell: "Three manages impressions; Six manages threats." },
  "3-7": { shared: "Both are fast, optimistic multitaskers who hate being stuck.",
           tell: "Three finishes for the trophy; Seven often leaves before the end." },
  "3-8": { shared: "Both are commanding, goal-driven, and comfortable taking charge.",
           tell: "Three adapts itself to win approval; Eight doesn't notice approval exists." },
  "3-9": { shared: "Both adapt smoothly to others' expectations.",
           tell: "Three adapts to impress; Nine adapts to disappear." },
  "4-5": { shared: "Both are withdrawn depth-seekers with rich inner worlds — 4w5 and 5w4 blur.",
           tell: "Four processes by feeling; Five by thinking." },
  "4-6": { shared: "Both are doubt-prone and braced for disappointment.",
           tell: "Four doubts its own worth; Six doubts the world's reliability." },
  "4-7": { shared: "Both crave intensity of experience and dread the mundane.",
           tell: "Four intensifies life through its pain; Seven through its pleasures." },
  "4-8": { shared: "Both are intense, authenticity-demanding, and unafraid of big emotions.",
           tell: "Four's intensity turns inward and broods; Eight's turns outward and moves." },
  "4-9": { shared: "Both are dreamy withdrawers who idealize what's missing.",
           tell: "Four sharpens feelings to feel real; Nine blurs them to stay comfortable." },
  "5-6": { shared: "Both are cautious head types who research before trusting — 5w6 and 6w5 blur.",
           tell: "Five trusts knowledge once earned; Six keeps re-checking even the knowledge." },
  "5-7": { shared: "Both are curious idea-generators who live largely in the mind.",
           tell: "Five goes deep on one thing; Seven goes wide on everything." },
  "5-8": { shared: "Both are fiercely independent and hate being controlled or intruded on.",
           tell: "Five defends with walls; Eight defends with force." },
  "5-9": { shared: "Both are low-demand withdrawers, and among the most-confused pairs in practice.",
           tell: "Five's inner world is precise; Nine's is ambient." },
  "6-7": { shared: "Both are quick-minded head types managing fear — 6w7 and 7w6 blur.",
           tell: "Six manages fear by preparing for it; Seven by outrunning it." },
  "6-8": { shared: "Both are protective, loyalty-testing, and alert to betrayal — counterphobic Six mimics Eight.",
           tell: "Six's aggression runs on anxiety; Eight's runs on instinct, with no fear engine underneath." },
  "6-9": { shared: "Both crave security and support, and dislike disruptive change.",
           tell: "Six scans and questions; Nine settles and soothes." },
  "7-8": { shared: "Both are assertive, appetite-driven, and take up space — 7w8 and 8w7 blur.",
           tell: "Seven asserts to stay free; Eight asserts to stay in control." },
  "7-9": { shared: "Both are optimists who avoid pain and keep things pleasant.",
           tell: "Seven avoids pain by acceleration; Nine by sedation." },
  "8-9": { shared: "Both are grounded gut types with legendary stubbornness — 8w9 and 9w8 blur.",
           tell: "Eight's power is loud and forward-moving; Nine's is quiet and immovable." }
};

/* The nine wing mirrors: adjacent blends that photograph almost identically. */
const WING_MIRRORS = [
  { pair: "1w2 vs 2w1", how: "Both are dutiful helpers with standards — the 1w2 corrects you for your own good; the 2w1 helps you the proper way." },
  { pair: "2w3 vs 3w2", how: "Both charm and shine — the 2w3 performs to earn closeness; the 3w2 warms people to earn wins." },
  { pair: "3w4 vs 4w3", how: "Both are stylish and self-aware — the 3w4 markets its depth; the 4w3 dramatizes its brand." },
  { pair: "4w5 vs 5w4", how: "Both are eccentric inner-world dwellers — the 4w5 feels its way to ideas; the 5w4 thinks its way to feelings." },
  { pair: "5w6 vs 6w5", how: "Both are careful system-builders — the 5w6 seeks certainty through knowledge; the 6w5 seeks knowledge for certainty." },
  { pair: "6w7 vs 7w6", how: "Both are quick, nervously funny company — the 6w7 jokes to manage fear; the 7w6 keeps moving so fear can't land." },
  { pair: "7w8 vs 8w7", how: "Both are big-appetite adventurers — the 7w8 wants freedom with muscle behind it; the 8w7 wants power with adventure in it." },
  { pair: "8w9 vs 9w8", how: "Both are calm until crossed — the 8w9 is force at rest; the 9w8 is rest with force in reserve." },
  { pair: "9w1 vs 1w9", how: "Both are quiet, orderly idealists — the 9w1 keeps the peace by being good; the 1w9 stays good by keeping the peace." }
];

if (typeof module !== "undefined") {
  module.exports = { PAIRS, SIMILAR, WING_MIRRORS, pairKey };
}
